apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: student-n-aichinger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: app
            - name: POSTGRES_USER
              value: app
            - name: POSTGRES_DB
              value: carsdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars
  namespace: student-n-aichinger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cars
  template:
    metadata:
      labels:
        app: cars
    spec:
      containers:
        - name: cars
          image: ghcr.io/naichinger/sypdemo:latest
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: "jdbc:postgresql://cars-db-svc:5432/carsdb"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cars-svc
  namespace: student-n-aichinger
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: cars
---
apiVersion: v1
kind: Service
metadata:
  name: cars-db-svc
  namespace: student-n-aichinger
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: db
  selector:
    app: database
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cars-ingress
  namespace: student-n-aichinger
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: student.cloud.htl-leonding.ac.at
      http:
        paths:
          - path: /n.aichinger/cars(.*)$
            pathType: Prefix
            backend:
              service:
                name: cars-svc
                port:
                  number: 80
