version: '3.8'

services:
    database:
      image: postgres:latest
      environment:
        POSTGRES_PASSWORD: app
        POSTGRES_USER: app
        POSTGRES_DB: carsdb
        PGDATA: "/var/lib/postgresql/data/pgdata"
      #volumes:
      #  - "./db:/var/lib/postgresql/data"
    web:
      image: nginx
      ports:
        - "8082:80"
    backend:
      image: demoapp
      ports:
        - "8080:8080"
